# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, v1.x ]
  pull_request:
    branches: [ master, v1.x ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix : 
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 11, 14-ea]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-2
    - name: Running tests
      run: mvn test
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
